version: '3.8'

services:
  web:
    build: ./django_report
    command: >
      sh -c "python manage.py flush --no-input
             python manage.py migrate
             python manage.py collectstatic --no-input
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django_report/:/django_report/
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: ./django_report
    command: python -m celery -A django_report.celery worker -l info
    volumes:
      - ./django_report:/django_report
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: