# Generated by Django 4.1.3 on 2022-12-02 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new_report', max_length=100, verbose_name='название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='расчет запрошен')),
                ('calc_time', models.FloatField(blank=True, null=True, verbose_name='время расчета')),
                ('date_start', models.DateField(verbose_name='дата начала')),
                ('date_fin', models.DateField(verbose_name='дата окончания')),
                ('lag', models.IntegerField(verbose_name='переодичность')),
                ('status', models.CharField(choices=[('completed', 'закончен'), ('in progress', 'выполняется'), ('in queue', 'в очереди')], default=('in queue', 'в очереди'), max_length=50, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
            },
        ),
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('liquid', models.FloatField(verbose_name='жидкость')),
                ('oil', models.FloatField(verbose_name='нефть')),
                ('water', models.FloatField(verbose_name='вода')),
                ('wct', models.FloatField(verbose_name='обводненность')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_frames', to='oil_report.report', verbose_name='расчет')),
            ],
            options={
                'verbose_name': 'Данные расчета',
                'verbose_name_plural': 'Данные расчетов',
            },
        ),
    ]
